/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "apvalue.h"
 #include <unistd.h>
 #include <string.h>

bool_t
xdr_apvaltype(xdrs, objp)
	XDR *xdrs;
	apvaltype *objp;
{

	if (!xdr_enum(xdrs, (enum_t *)objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_aptag(xdrs, objp)
	XDR *xdrs;
	aptag *objp;
{

	if (!xdr_enum(xdrs, (enum_t *)objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_apindex(xdrs, objp)
	XDR *xdrs;
	apindex *objp;
{

	if (!xdr_aptag(xdrs, &objp->tag))
		return (FALSE);
	switch (objp->tag) {
	case AP_NONE:
		break;
	case AP_ARRAY_STYLE:
		if (!xdr_int(xdrs, &objp->apindex_u.x))
			return (FALSE);
		break;
	case AP_STRUCT_STYLE:
		if (!xdr_string(xdrs, &objp->apindex_u.s, ~0))
			return (FALSE);
		break;
	default:
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_apvalue(xdrs, objp)
	XDR *xdrs;
	apvalue *objp;
{

	if (!xdr_apvaltype(xdrs, &objp->type))
		return (FALSE);
	switch (objp->type) {
	case AP_INT:
		if (!xdr_int64_t(xdrs, &objp->apvalue_u.asInt))
			return (FALSE);
		break;
	case AP_FLOAT:
		if (!xdr_double(xdrs, &objp->apvalue_u.asFloat))
			return (FALSE);
		break;
	case AP_BOOL:
		if (!xdr_bool(xdrs, &objp->apvalue_u.asBool))
			return (FALSE);
		break;
	case AP_TIME:
		if (!xdr_int64_t(xdrs, &objp->apvalue_u.asTime))
			return (FALSE);
		break;
	case AP_DURATION:
		if (!xdr_int64_t(xdrs, &objp->apvalue_u.asDuration))
			return (FALSE);
		break;
	case AP_STRING:
		if (!xdr_string(xdrs, &objp->apvalue_u.asString, ~0))
			return (FALSE);
		break;
	case AP_INSTANCE:
		if (!xdr_string(xdrs, &objp->apvalue_u.asInstance, ~0))
			return (FALSE);
		break;
	case AP_ARRAY:
		break;
	case AP_STRUCT:
		break;
	default:
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_aparrayelement(xdrs, objp)
	XDR *xdrs;
	aparrayelement *objp;
{

	if (!xdr_apvalue(xdrs, &objp->content))
		return (FALSE);
	if (!xdr_apindex(xdrs, &objp->indx))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->apid))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->parent))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_aparray(xdrs, objp)
	XDR *xdrs;
	aparray *objp;
{

	if (!xdr_array(xdrs, (char **)&objp->apvector.apvector_val, (u_int *)&objp->apvector.apvector_len, ~0, sizeof(aparrayelement), (xdrproc_t)xdr_aparrayelement))
		return (FALSE);
	return (TRUE);
}
