#if HAVE_CONFIG_H
#include <config.h>
#endif

#include "gramgen.H"

//
// Assumption: the 'dsl' token indicates the name of the classes
// that support the parser. In particular, a class named
// 	<dsl>Exp
//
// is supposed to exist, and a numnber of utilities are expected
// in namespace <dsl>.
//
// Assumption: output files generated by bison will start with
// <prefix>.
//
// This assumption is a first, crude attempt to make the syntax
// generator as generic as possible.
//
void write_bison_preamble(
	stringstream& str,
	const string& dsl,
	const string& prefix) {
    str << "%output \"" << prefix << "_grammar.C\"\n";
    str << "%defines \"" << prefix << "_grammar.H\"\n";
    str << "\n";
    str << "%define api.pure full\n";
    str << "%define parse.trace\n";
    str << "%lex-param { yyscan_t scanner }\n";
    str << "%parse-param { yyscan_t scanner }\n";
    str << "\n";
    str << "%code requires {\n";
    str << "#include \"" << dsl << "Reader.H\"\n";
    str << "\n";
    str << "//\n";
    str << "// " << prefix << "_tokens.H needs this:\n";
    str << "//\n";
    str << "#define YYSTYPE " << dsl << "Exp\n";
    str << "\n";

    //
    // Nasty side effects occur if we include the generated
    // scanner header file; it undefines various things.
    // The scanner absolutely needs the parser header
    // file, which contains the token definitions. We
    // have no choice but omit the scanner include file
    // here.
    //
    // str << "#include \"" << prefix << "_tokens.H\"\n";
    str << "#ifndef YY_TYPEDEF_YY_SCANNER_T\n";
    str << "#define YY_TYPEDEF_YY_SCANNER_T\n";
    str << "typedef void *yyscan_t;\n";
    str << "#endif\n\n";
    str << "extern int yylex (YYSTYPE* yylval_param, yyscan_t yyscanner);\n\n";
    str << "}\n";
    str << "\n";
    str << "%code {\n";
    str << "#include \"" << dsl << "_expressions.H\"\n";
    str << "using namespace " << dsl << ";\n";
    str << "\n";
    str << "//\n";
    str << "// defined in " << dsl << "_lexer_support.C:\n";
    str << "//\n";
    str << "extern int yyerror(yyscan_t scanner, const char* msg);\n";
    str << "}\n";
    str << "\n";
    str << "%define api.value.type { " << dsl << "Exp }\n";
}
