#! /bin/sh

set -x

case `uname` in
	Darwin)
		TOOLIZE=glibtoolize ;;
	Linux)
		TOOLIZE=libtoolize ;;
	*)
		TOOLIZE=libtoolize ;;
esac

aclocal \
&& $TOOLIZE --automake \
&& autoheader \
&& automake --gnu --add-missing \
&& autoconf
